// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckAll():Promise<void>;

export function CheckOne(arg1:string,arg2:number):Promise<void>;

export function ChooseDownloadDir():Promise<string>;

export function DownloadAll():Promise<void>;

export function DownloadDir():Promise<string>;

export function DownloadOne(arg1:string,arg2:number):Promise<void>;

export function ListProviderVariants():Promise<Array<main.VariantSetting>>;

export function ListProviders():Promise<Array<main.ProviderInfo>>;

export function RescanFound():Promise<void>;

export function SetAllVariantsEnabled(arg1:boolean):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function SetVariantEnabled(arg1:string,arg2:number,arg3:boolean):Promise<void>;

export function Theme():Promise<string>;

export function ValidateAll():Promise<void>;

export function ValidateOne(arg1:string,arg2:number):Promise<void>;
