// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAll() {
  return window['go']['main']['App']['CheckAll']();
}

export function CheckOne(arg1, arg2) {
  return window['go']['main']['App']['CheckOne'](arg1, arg2);
}

export function ChooseDownloadDir() {
  return window['go']['main']['App']['ChooseDownloadDir']();
}

export function DownloadAll() {
  return window['go']['main']['App']['DownloadAll']();
}

export function DownloadDir() {
  return window['go']['main']['App']['DownloadDir']();
}

export function DownloadOne(arg1, arg2) {
  return window['go']['main']['App']['DownloadOne'](arg1, arg2);
}

export function ListProviderVariants() {
  return window['go']['main']['App']['ListProviderVariants']();
}

export function ListProviders() {
  return window['go']['main']['App']['ListProviders']();
}

export function RescanFound() {
  return window['go']['main']['App']['RescanFound']();
}

export function SetAllVariantsEnabled(arg1) {
  return window['go']['main']['App']['SetAllVariantsEnabled'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function SetVariantEnabled(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetVariantEnabled'](arg1, arg2, arg3);
}

export function Theme() {
  return window['go']['main']['App']['Theme']();
}

export function ValidateAll() {
  return window['go']['main']['App']['ValidateAll']();
}

export function ValidateOne(arg1, arg2) {
  return window['go']['main']['App']['ValidateOne'](arg1, arg2);
}
